# Generated by Django 4.1.7 on 2023-03-19 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='desc',
            field=models.TextField(),
        ),
    ]
